version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U people -d people"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro,Z
    command: ["-source","file:///migrations","-database","postgres://people:people@db:5432/people?sslmode=disable","up"]
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DSN: postgres://people:people@db:5432/people?sslmode=disable
      HTTP_ADDR: 0.0.0.0:8080
      LOG_LEVEL: info
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8082:8080"
    restart: unless-stopped

  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml:ro
    ports:
      - "8081:8080"

volumes:
  pgdata:
